name: Test
on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Perform tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: Code Coverage
        uses: codecov/codecov-action@v1
